name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *' # runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: rashhiye
          # Optional: color your snake
          color: '33cc33'
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Commit & push SVGs
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Update GitHub contribution snake"
          add: "dist/*.svg"
